resource_group_name = "myrg"
location            = "East US"
admin_login         = "adminuser"
admin_password      = "Password123!"
sql_server_name     = "mysqlserver1"
sql_db_name         = "mysqldb"
