resource_group_name = "myrg2"
location            = "East US"
admin_login         = "adminuser"
admin_password      = "Password123!"
sql_server_name     = "mysqlserverdevtest1"
sql_db_name         = "mysqldbdevtest"
