resource_group_name = "myrg5"
location            = "East US"
admin_login         = "adminuser"
admin_password      = "Password123!"
sql_server_name     = "mysqlserverdevtest3"
sql_db_name         = "mysqldbdevtest3"
